---
title: "Untitled"
author: "Anh Tran"
date: "4/3/2022"
output: html_document
---
# This part will involve all classification models

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Remove previous data from environment
rm(list = ls())
```

```{r include=FALSE}
if (!require("sjPlot")) install.packages("sjPlot")
if (!require("tidyverse")) install.packages("sjPlot")

library(arrow) # needed to read parquet file

library(dplyr)
library(car)
library(caret)
library(rattle)
library(rpart.plot)
library(rpart)
library(ggplot2)
library(corrplot)
library(sjPlot)
library(gridExtra)
library(tidyverse)
library(rsample)
library(randomForest)
library(janitor)
library(glmnet)
library(tree)
library(RColorBrewer)
library(gridExtra)
library(pls)
```


```{r}
file_path <- "../04_Modeling/df_num_impute0.parquet"
df1 <- read_parquet(file_path, as_tibble = TRUE)
View(df1)
```

### Note:  This file exclude 2 columns of "date" 

```{r}
df = as.data.frame(df1[,c(2,3,5,6,12,13,14)]) # standardize all numerical variables

df <- cbind(df1[,c(1,4,7,8,9,10,11,16,17,18,19)],df,df1[,15]) # Add categorical columns  back in

View(df)
```

```{r}
summary(df$totalinsurancepremiumofthepolicy)
```


# Splitting data to 70% training, 30% testing

```{r}
set.seed(100)

size <- floor(0.7*nrow(df))
train_ind <- sample(seq_len(nrow(df)), size = size)

train <- df[train_ind, ]
test <- df[-train_ind, ]
```

#1. Linear Regression: Ridge and Lasso

```{r}
rsquared <- function(pred){
  if (length(pred)==length(test$totalinsurancepremiumofthepolicy)){
    r2 = 1 - (sum((test$totalinsurancepremiumofthepolicy-pred)^2)/sum((test$totalinsurancepremiumofthepolicy-mean(test$totalinsurancepremiumofthepolicy))^2))
  }
  if (length(pred)==length(train$totalinsurancepremiumofthepolicy)){
    r2 = 1 - (sum((train$totalinsurancepremiumofthepolicy-pred)^2)/sum((train$totalinsurancepremiumofthepolicy-mean(train$totalinsurancepremiumofthepolicy))^2))
  }
  return (r2)
}


MSE <- function(pred){
  if (length(pred)==length(test$totalinsurancepremiumofthepolicy)){
    mse = sum((test$totalinsurancepremiumofthepolicy-pred)^2)/length(test$totalinsurancepremiumofthepolicy)
  }
  if (length(pred)==length(train$totalinsurancepremiumofthepolicy)){
    mse = sum((train$totalinsurancepremiumofthepolicy-pred)^2)/length(train$totalinsurancepremiumofthepolicy)
  }
  return (mse)
}
```

## 1. Ridge
```{r}
xtrain = model.matrix(totalinsurancepremiumofthepolicy ~.,train)[,-1]
ytrain = train$totalinsurancepremiumofthepolicy
xtest = model.matrix(totalinsurancepremiumofthepolicy ~.,test)[,-1]
ytest = test$totalinsurancepremiumofthepolicy
```

```{r}
grid = 10^seq(10, -2, length=100)

cv.ridge.out = cv.glmnet(xtrain, ytrain, alpha=0)
bestlam.ridge = cv.ridge.out$lambda.min
i <- which(cv.ridge.out$lambda == cv.ridge.out$lambda.min)
mse.min.ridge <- cv.ridge.out$cvm[i]

ridge.model = glmnet(xtrain, ytrain, alpha=0, lambda=bestlam.ridge)

ridge.pred.train = predict(ridge.model, newx=xtrain)
mse.ridge.train = MSE(ridge.pred.train)
r2.ridge.train = rsquared(ridge.pred.train)

ridge.pred.test = predict(ridge.model, newx=xtest)
mse.ridge.test = MSE(ridge.pred.test)
r2.ridge.test = rsquared(ridge.pred.test)
```


## 2. Lasso
```{r}

cv.lasso.out = cv.glmnet(xtrain, ytrain, alpha=1)
bestlam.lasso = cv.lasso.out$lambda.min
i <- which(cv.lasso.out$lambda == cv.lasso.out$lambda.min)
mse.min.lasso <- cv.lasso.out$cvm[i]

lasso.model = glmnet(xtrain, ytrain, alpha=1, lambda=bestlam.lasso)

lasso.pred.train = predict(lasso.model, newx=xtrain)
mse.lasso.train = MSE(lasso.pred.train)
r2.lasso.train = rsquared(lasso.pred.train)

lasso.pred.test = predict(lasso.model, newx=xtest)
mse.lasso.test = MSE(lasso.pred.test)
r2.lasso.test = rsquared(lasso.pred.test)
```

```{r}
ggplot(mapping = aes(x=log(cv.ridge.out$lambda), y=cv.ridge.out$cvm)) +
  geom_point() +
  geom_point(aes(x=log(bestlam.ridge), y=mse.min.ridge, color="blue", size = 2), show.legend = FALSE, color="blue") +
  geom_errorbar(aes(ymin=cv.ridge.out$cvm-cv.ridge.out$cvsd, ymax=cv.ridge.out$cvm+cv.ridge.out$cvsd), color="gray") +
  xlab("Log(lambda)") +
  ylab("Mean Squared Error") +
  labs(title = "Optimal Lambda for Ridge Regression", subtitle = paste("Best Lambda: ", bestlam.ridge)) +
  theme_classic()
dev.copy(jpeg, filename="Ridge_Lambda.jpg");
dev.off ()



ggplot(mapping = aes(x=log(cv.lasso.out$lambda), y=cv.lasso.out$cvm)) +
  geom_point() +
  geom_point(aes(x=log(bestlam.lasso), y=mse.min.lasso, size = 2), show.legend = FALSE, color="red") +
  geom_errorbar(aes(ymin=cv.lasso.out$cvm-cv.lasso.out$cvsd, ymax=cv.lasso.out$cvm+cv.lasso.out$cvsd), color="gray") +
  xlab("Log(lambda)") +
  ylab("Mean Squared Error") +
  labs(title = "Optimal Lambda for Lasso Regression", subtitle = paste("Best Lambda: ", bestlam.lasso)) +
  theme_classic()
dev.copy(jpeg, filename="Lasso_Lambda.jpg");
dev.off ()
```


```{r}
ridge.coef <- rownames_to_column(data.frame(coef(ridge.model)[,1]), var = "Variable") %>%
  rename(Coefficient = coef.ridge.model....1.)

ridge.coef <- ridge.coef %>%
  filter(Variable != "(Intercept)") %>%
  arrange(desc(abs(Coefficient)))
lasso.coef <- rownames_to_column(data.frame(coef(lasso.model)[,1]), var = "Variable") %>%
  rename(Coefficient = coef.lasso.model....1.)

lasso.coef <- lasso.coef %>%
  filter(Variable != "(Intercept)") %>%
  arrange(desc(abs(Coefficient)))

coef.compare <- lasso.coef %>%
  left_join(ridge.coef, by = "Variable") %>%
  rename("Lasso Coefficient" = Coefficient.x) %>%
  rename("Ridge Coefficient" = Coefficient.y)

coef.compare
write.csv(coef.compare,"../04_Modeling/Ridge_Lasso_Lambda", row.names = FALSE)
```

```{r}
plot1 <- ggplot(mapping = aes(x = test$totalinsurancepremiumofthepolicy, y = ridge.pred.test)) +
  geom_point(color = "red") +
  geom_abline(slope = 1) +
  xlab("Predicted Insurance Premium") +
  ylab("Actual Insurance Premium") +
  labs(title = "Ridge Regression")

plot2 <- ggplot(mapping = aes(x = test$totalinsurancepremiumofthepolicy, y = lasso.pred.test)) +
  geom_point(color = "blue") +
  geom_abline(slope = 1) +
  xlab("Predicted Insurance Premium") +
  ylab("Actual Insurance Premium") +
  labs(title = "Lasso")

grid.arrange(plot1, plot2, nrow = 2)

dev.copy(jpeg, filename="Ridge_Lasso_Plot.jpg")
dev.off ()
```


# Bagging or random forest (can not run due to memory limit)
```{r}
set.seed(100)

bag.model <- randomForest(totalinsurancepremiumofthepolicy ~., data = train, mtry = 10, importance = TRUE)

pred.bag.train <- predict(bag.model, train)
mse.bag.train <- MSE(pred.bag.train)
r2.bag.train <- rsquared(pred.bag.train)

pred.bag.test <- predict(bag.model, test)
mse.bag.test <- MSE(pred.bag.test)
r2.bag.test <- rsquared(pred.bag.test)
```



# Bossting
```{r}
set.seed(100)
boost.model <- gbm(totalinsurancepremiumofthepolicy ~., data = train, distribution = "gaussian", n.trees = 5000, interaction.depth = 4)

pred.boost.train <- predict(boost.model, train)
```


```{r}
mse.boost.train <- MSE(pred.boost.train)
r2.boost.train <- rsquared(pred.boost.train)

pred.boost.test <- predict(boost.model, test)
```


```{r}
mse.boost.test <- MSE(pred.boost.test)
r2.boost.test <- rsquared(pred.boost.test)
```


```{r}
df2 <- data.frame(summary(boost.model, plotit = FALSE), row.names = NULL)
ggplot(df, aes(x=reorder(var,rel.inf), y=rel.inf, fill=reorder(var,rel.inf))) +
  geom_col(show.legend = FALSE) +
  coord_flip() +
  labs(title = "Relative Influence of Variables in Predicting Insurance Premium") +
  ylab("Relative Influence") +
  xlab("") +
  scale_fill_manual(values = colorRampPalette(brewer.pal(1,"Oranges"))(10)) +
  theme_classic()
```




#2. PCA

```{r}
#PCA
library(stats)  # for prcomp()
library(DAAG)
library(GGally)
library(devtools)
require(ggbiplot)
```


```{r}
PCA <- prcomp(train[,1:18], scale = TRUE)  # apply PCA

summary(PCA)
```


```{r}
# Common function to display PCA related plots in 2x2 grid
screeplot(PCA, type='l')
dev.copy(jpeg, filename="PCA_ScreePlot.jpg")
dev.off ()

bplot = ggbiplot(PCA,
                 choices = c(1,2),
                 obs.scale =1, var.scale =1,
                 circle = TRUE,
                 ellipse = TRUE,
                 ellipse.prob = 0.68)

print(bplot)

dev.copy(jpeg, filename="PCA_Plot.jpg")
dev.off ()

```

```{r}
pca.pred4 = predict(PCA, test[,1:18])
```






















