---
title: "Visualization"
author: "Anh Tran"
date: "4/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Remove previous data from environment
rm(list = ls())
```

```{r include=FALSE}

library(arrow) # needed to read parquet file
library(plyr)
library(dplyr)
library(car)
library(caret)
library(rattle)
library(rpart.plot)
library(rpart)
library(ggplot2)
library(corrplot)
library(tidyr)
```

```{r}
file_path <- "../03_EDA/df_final.parquet"
df <- read_parquet(file_path, as_tibble = TRUE)
#View(df)
str(df)
```


```{r}
df_num <- subset(df, select = c(crsdiscount,latitude, longitude, policycost, totalbuildinginsurancecoverage, totalcontentsinsurancecoverage))

# categorical variables
df_cat <- subset(df, select = -c(crsdiscount,latitude, longitude, policycost, totalbuildinginsurancecoverage, totalcontentsinsurancecoverage))
```


```{r}
pairs(df[c("crsdiscount","latitude", "longitude", "policycost", "totalbuildinginsurancecoverage", "totalcontentsinsurancecoverage", "totalinsurancepremiumofthepolicy")])
```

