---
title: "CleanData"
author: "MJ"
date: "24/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Remove previous data from environment
rm(list = ls())
```

```{r}
library(arrow) # needed to read parquet file
library(dplyr)
library(car)
library(caret)
library(ggplot2)
library(corrplot)
```

## Read & View the Data
```{r}
# path to the project folder
#setwd("C:/Users/mjafarpour/Downloads/MGT_6203_GroupProject/")
file_path <- "../01_RawData/nfip_Houston_flood_policies.parquet"
policy_df <- read_parquet(file_path, as_tibble = TRUE)
head(policy_df)
```

## I filter the dataset again for Texas only 
```{r}
## Filter propertystate = 'TX"
policy_df <- subset(policy_df, propertystate == 'TX' )
```


```{r}
policy_df = subset(policy_df,select=-c(agriculturestructureindicator, propertystate, reportedcity, houseofworshipindicator,nonprofitindicator,regularemergencyprogramindicator,smallbusinessindicatorbuilding,hfiaasurcharge))
View(policy_df)
```

```{r}
# count NA values in each column
colSums(is.na(policy_df))
```

## Continue fiter some columns with large number of NA

```{r}
# Filter more columns with significant number of NA values
policy_df = subset(policy_df,select=-c(basefloodelevation,cancellationdateoffloodpolicy, countycode, elevationcertificateindicator, lowestadjacentgrade, lowestfloorelevation, obstructiontype))                          
View(policy_df)
```

```{r}
# Number of NA values in each column
colSums(is.na(policy_df))
```
```{r}
## Observe unique value in each column

categorical_col <- policy_df[c("condominiumindicator", "construction", "elevatedbuildingindicator", "floodzone", "locationofcontents", "postfirmconstructionindicator", "primaryresidenceindicator")]

count_unique <- rapply(categorical_col, function(x) length(unique(x)))
count_unique
```
## Some category variable neeed to clarify:
## condominiumindicator (6), construction (3), elevatedbuildingindicator(3), floodzone (33), locationofcontents (7), postfirmconstructionindicator (3), primaryresidenceindicator (3)
```{r}
# condominiumindicator variables

unique(policy_df$condominiumindicator)
unique(policy_df$locationofcontents)

```
```{r}
#condominum indicator for lower level and upper level condo
policy_df$lowerlevelcondo=ifelse(policy_df$condominiumindicator=='L',1,0)
policy_df$upperlevelcondo=ifelse(policy_df$condominiumindicator=='U',1,0)

# Construction
policy_df$construction=ifelse(policy_df$construction=='Y',1,0)

#elevatedbuildingindicator
policy_df$elevatedbuildingindicator=ifelse(policy_df$elevatedbuildingindicator=='Y',1,0)


#trying to factor the locationofcontents column ....feel free to advise anyother column names. 
policy_df$lowerflooronly=ifelse(policy_df$locationofcontents=='Lowest floor only above ground level (No basement/enclosure/crawlspace/subgrade crawlspace)',1,0)
policy_df$upperandlowerfloors=ifelse(policy_df$locationofcontents=='Lowest floor above ground level and higher floors (No basement/enclosure/crawlspace/subgrade crawlspace)',1,0)
policy_df$basementandabove=ifelse(policy_df$locationofcontents=='Basement/Enclosure/Crawlspace/Subgrade Crawlspace and above',1,0)
policy_df$basementonly=ifelse(policy_df$locationofcontents=='Basement/Enclosure/Crawlspace/Subgrade Crawlspace only',1,0)
policy_df$morethan1floor=ifelse(policy_df$locationofcontents=='Above ground level more than one full floor',1,0)
policy_df$mobilehomeortrailer=ifelse(policy_df$locationofcontents==' Manufactured (mobile) home or travel trailer on foundation',1,0)

#postfirmconstructionindicator
policy_df$postfirmconstructionindicator=ifelse(policy_df$postfirmconstructionindicator=='Y',1,0)

#primaryresidenceindicator
policy_df$primaryresidenceindicator=ifelse(policy_df$primaryresidenceindicator=='Y',1,0)
```


```{r}
# Continue remove category variables

df = subset(policy_df,select=-c(condominiumindicator, locationofcontents))
View(df)
```


```{r}
## Type of data in all columns
str(df)
```
```{r}
# Convert all date from numeric to date format

date_cols <- c("originalconstructiondate", "originalnbdate", "policyeffectivedate", "policyterminationdate")

df1 <- df %>%
   mutate_at(vars(all_of(date_cols)), funs(as.Date(., "%Y-%m-%d")))

str(df1)
```

```{r}
#floodzones
# high risk if starts with A or V
df1$floodzone_highrisk <- ifelse( (startsWith(df1$floodzone, 'A') | (startsWith(df1$floodzone, 'V'))),1,0)
# moderate-to-low risk if starts with B, C or X
df1$floodzone_modrisk <- ifelse( (startsWith(df1$floodzone, 'B') | (startsWith(df1$floodzone, 'C')) | (startsWith(df1$floodzone, 'X'))),1,0)
# possible but undetermined flood hazards: starts with D
df1$floodzone_undetermined <- ifelse( (startsWith(df1$floodzone, 'D')) ,1,0)
```


```{r}
#identify all character columns
df2 <- subset(df1, select = -c(floodzone))
# ratemethod should also be categorical; 1 - Manual 2 - Specific 3 - Alternative 4 - V-Zone Risk Factor Rating Form 5 - Underinsured Condominium Master Policy 6 - Provisional 7 - Preferred Risk Policy (PRPs issued for eligible properties located within a non-Special Flood Hazard Area [non-SFHA]) 8 - Tentative 9 - MPPP Policy 

chars <- sapply(df2, is.character)

#convert all character columns to numeric
df2[ , chars] <- as.data.frame(apply(df2[ , chars], 2, as.numeric))
str(df2)
```
```{r}
# Exporting the dataframe to clean folder
file_path2 <- "../02_CleanData/policy_clean.parquet"
write_parquet(df2, file_path2)
```

